name: apiTask
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  json_annotation: ^4.1.0
  http: ^0.13.4
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^5.0.2
  build_runner: 


flutter:

  uses-material-design: true
  assets:
    - assets/gif/
